import { collection, doc, getDocs, limit, orderBy, query, updateDoc, where } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import type { LearningProgressSummary } from "./progressSummary";
import { firebaseFunctions, firestore } from "./firebaseClient";

export type ProgressReportShare = { id: string; family_id: string; summary_id: string; child_id: string | null; created_by: string | null; audience: "parent" | "teacher" | "coach" | "meeting" | "email" | "custom"; language: "zh" | "en" | "bilingual"; title: string; content_markdown: string; email_subject: string | null; email_body: string | null; key_points: string[]; questions: string[]; action_items: string[]; privacy_notes: string[]; status: "draft" | "final" | "archived"; created_at: string; updated_at: string; };

function withId<T>(snapshot: { id: string; data: () => Record<string, unknown> }) { return { id: snapshot.id, ...snapshot.data() } as T; }
export function markdownToPlainText(markdown: string) { return markdown.replace(/^#{1,6}\s+/gm, "").replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/^- /gm, "- ").trim(); }
function escapeHtml(value: string) { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
function markdownToHtml(markdown: string) { return markdown.split("\n").map((line) => { if (line.startsWith("### ")) return `<h3>${escapeHtml(line.slice(4))}</h3>`; if (line.startsWith("## ")) return `<h2>${escapeHtml(line.slice(3))}</h2>`; if (line.startsWith("# ")) return `<h1>${escapeHtml(line.slice(2))}</h1>`; if (line.startsWith("- ")) return `<div>&bull; ${escapeHtml(line.slice(2))}</div>`; if (!line.trim()) return `<br />`; return `<p>${escapeHtml(line)}</p>`; }).join("\n"); }

export function buildSummaryMarkdown(summary: LearningProgressSummary, childName: string) {
  const sections = [`# ${summary.title}`, "", `**Child:** ${childName}`, `**Period:** ${summary.period_start} to ${summary.period_end}`, summary.subject ? `**Subject:** ${summary.subject}` : "", `**Evidence count:** ${summary.evidence_count}`, `**Confidence:** ${Math.round(Number(summary.confidence) * 100)}%`, "", "## Executive summary", summary.executive_summary, "", "## Professional narrative", summary.narrative_text, "", "## Strengths", ...summary.strengths.map((item) => `- ${item}`), "", "## Concerns / areas for improvement", ...summary.concerns.map((item) => `- ${item}`), "", "## Observed patterns", ...summary.observed_patterns.map((item) => `- ${item}`), "", "## Recommendations", ...summary.recommendations.map((item) => `- ${item}`), "", "## Parent actions", ...summary.parent_actions.map((item) => `- ${item}`), "", "## Child actions", ...summary.child_actions.map((item) => `- ${item}`), "", "## Teacher / coach questions", ...summary.teacher_questions.map((item) => `- ${item}`), "", "## Next goals", ...summary.next_goals.map((item) => `- ${item}`), "", "## Missing evidence", ...(summary.missing_evidence.length ? summary.missing_evidence.map((item) => `- ${item}`) : ["- No major missing evidence was identified."])].filter(Boolean);
  return sections.join("\n");
}

export function buildPrintableHtml(args: { title: string; markdown: string; childName?: string; generatedLabel?: string; }) {
  const html = markdownToHtml(args.markdown);
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(args.title)}</title></head><body><header><h1>${escapeHtml(args.title)}</h1><p>${escapeHtml(args.generatedLabel ?? "Generated by Family Dock")}</p></header><main>${html}</main></body></html>`;
}
export function openPrintWindow(title: string, markdown: string) { const html = buildPrintableHtml({ title, markdown }); const win = window.open("", "_blank"); if (!win) throw new Error("Popup blocked. Allow popups to open print view."); win.document.write(html); win.document.close(); }
export function downloadHtml(filename: string, title: string, markdown: string) { const html = buildPrintableHtml({ title, markdown }); const blob = new Blob([html], { type: "text/html;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename.endsWith(".html") ? filename : `${filename}.html`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
export function buildEmailDraft(subject: string, body: string) { window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }

export async function loadReportShares(familyId: string, summaryId: string) {
  const snap = await getDocs(query(collection(firestore, "families", familyId, "progress_report_shares"), where("summary_id", "==", summaryId), orderBy("created_at", "desc"), limit(30)));
  return snap.docs.map((docSnap) => withId<ProgressReportShare>(docSnap));
}

export async function generateReportShareVersion(args: { familyId: string; summaryId: string; audience: ProgressReportShare["audience"]; language: ProgressReportShare["language"]; customInstruction?: string | null; save?: boolean; }) {
  const fn = httpsCallable(firebaseFunctions, "generateReportShareVersion");
  const result = await fn({ family_id: args.familyId, summary_id: args.summaryId, audience: args.audience, language: args.language, custom_instruction: args.customInstruction ?? null, save: args.save ?? true });
  return result.data as { ok: boolean; saved: boolean; share: ProgressReportShare };
}

export async function updateReportShareStatus(args: { familyId: string; shareId: string; status: "draft" | "final" | "archived"; }) {
  await updateDoc(doc(firestore, "families", args.familyId, "progress_report_shares", args.shareId), { status: args.status, updated_at: new Date().toISOString() });
}
