import type { LearningProgressSummary } from "./progressSummary";
import { supabase } from "./supabaseClient";

export type ProgressReportShare = {
  id: string;
  family_id: string;
  summary_id: string;
  child_id: string | null;
  created_by: string | null;
  audience: "parent" | "teacher" | "coach" | "meeting" | "email" | "custom";
  language: "zh" | "en" | "bilingual";
  title: string;
  content_markdown: string;
  email_subject: string | null;
  email_body: string | null;
  key_points: string[];
  questions: string[];
  action_items: string[];
  privacy_notes: string[];
  status: "draft" | "final" | "archived";
  created_at: string;
  updated_at: string;
};

export function markdownToPlainText(markdown: string) {
  return markdown
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/^- /gm, "• ")
    .trim();
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function markdownToHtml(markdown: string) {
  const lines = markdown.split("\n");
  return lines.map((line) => {
    if (line.startsWith("### ")) return `<h3>${escapeHtml(line.slice(4))}</h3>`;
    if (line.startsWith("## ")) return `<h2>${escapeHtml(line.slice(3))}</h2>`;
    if (line.startsWith("# ")) return `<h1>${escapeHtml(line.slice(2))}</h1>`;
    if (line.startsWith("- ")) return `<li>${escapeHtml(line.slice(2))}</li>`;
    if (!line.trim()) return `<br />`;
    return `<p>${escapeHtml(line)}</p>`;
  }).join("\n").replace(/(<li>[\s\S]*?<\/li>)/g, "<ul>$1</ul>").replace(/<\/ul>\s*<ul>/g, "");
}

export function buildSummaryMarkdown(summary: LearningProgressSummary, childName: string) {
  const sections = [
    `# ${summary.title}`,
    "",
    `**Child:** ${childName}`,
    `**Period:** ${summary.period_start} to ${summary.period_end}`,
    summary.subject ? `**Subject:** ${summary.subject}` : "",
    `**Evidence count:** ${summary.evidence_count}`,
    `**Confidence:** ${Math.round(Number(summary.confidence) * 100)}%`,
    "",
    "## Executive summary",
    summary.executive_summary,
    "",
    "## Professional narrative",
    summary.narrative_text,
    "",
    "## Strengths",
    ...summary.strengths.map((item) => `- ${item}`),
    "",
    "## Concerns / areas for improvement",
    ...summary.concerns.map((item) => `- ${item}`),
    "",
    "## Observed patterns",
    ...summary.observed_patterns.map((item) => `- ${item}`),
    "",
    "## Recommendations",
    ...summary.recommendations.map((item) => `- ${item}`),
    "",
    "## Parent actions",
    ...summary.parent_actions.map((item) => `- ${item}`),
    "",
    "## Child actions",
    ...summary.child_actions.map((item) => `- ${item}`),
    "",
    "## Teacher / coach questions",
    ...summary.teacher_questions.map((item) => `- ${item}`),
    "",
    "## Next goals",
    ...summary.next_goals.map((item) => `- ${item}`),
    "",
    "## Missing evidence",
    ...(summary.missing_evidence.length ? summary.missing_evidence.map((item) => `- ${item}`) : ["- No major missing evidence was identified."]),
  ].filter(Boolean);

  return sections.join("\n");
}

export function buildPrintableHtml(args: {
  title: string;
  markdown: string;
  childName?: string;
  generatedLabel?: string;
}) {
  const html = markdownToHtml(args.markdown);
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(args.title)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
      color: #1c1917;
      margin: 0;
      background: #f6f1e8;
    }
    main {
      max-width: 860px;
      margin: 24px auto;
      background: white;
      padding: 36px;
      border-radius: 24px;
      box-shadow: 0 18px 60px rgba(92,74,54,.12);
    }
    h1 { font-size: 30px; letter-spacing: -0.03em; }
    h2 { margin-top: 30px; border-top: 1px solid #e7dccb; padding-top: 18px; }
    h3 { margin-top: 22px; }
    p, li { line-height: 1.65; font-size: 15px; }
    .meta {
      color: #73695f;
      font-weight: 700;
      margin-bottom: 24px;
    }
    @media print {
      body { background: white; }
      main { box-shadow: none; margin: 0; padding: 0; border-radius: 0; max-width: none; }
      button { display: none; }
    }
  </style>
</head>
<body>
  <main>
    <button onclick="window.print()" style="float:right;padding:10px 14px;border-radius:12px;border:1px solid #d6c7b2;background:white;font-weight:800;">Print / Save PDF</button>
    <div class="meta">${escapeHtml(args.generatedLabel ?? "Generated by Family Dock")}</div>
    ${html}
  </main>
</body>
</html>`;
}

export function openPrintWindow(title: string, markdown: string) {
  const html = buildPrintableHtml({ title, markdown });
  const win = window.open("", "_blank");
  if (!win) throw new Error("Popup blocked. Allow popups to open print view.");
  win.document.write(html);
  win.document.close();
}

export function downloadHtml(filename: string, title: string, markdown: string) {
  const html = buildPrintableHtml({ title, markdown });
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".html") ? filename : `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function buildEmailDraft(subject: string, body: string) {
  const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  window.location.href = mailto;
}

export async function loadReportShares(familyId: string, summaryId: string) {
  const { data, error } = await supabase
    .from("progress_report_shares")
    .select("*")
    .eq("family_id", familyId)
    .eq("summary_id", summaryId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return (data ?? []) as ProgressReportShare[];
}

export async function generateReportShareVersion(args: {
  familyId: string;
  summaryId: string;
  audience: ProgressReportShare["audience"];
  language: ProgressReportShare["language"];
  customInstruction?: string | null;
  save?: boolean;
}) {
  const { data, error } = await supabase.functions.invoke("ai-report-share-version", {
    body: {
      family_id: args.familyId,
      summary_id: args.summaryId,
      audience: args.audience,
      language: args.language,
      custom_instruction: args.customInstruction ?? null,
      save: args.save ?? true,
    },
  });

  if (error) throw error;
  return data as { ok: boolean; saved: boolean; share: ProgressReportShare };
}

export async function updateReportShareStatus(args: {
  familyId: string;
  shareId: string;
  status: "draft" | "final" | "archived";
}) {
  const { error } = await supabase
    .from("progress_report_shares")
    .update({ status: args.status })
    .eq("family_id", args.familyId)
    .eq("id", args.shareId);

  if (error) throw error;
}
