import { collection, doc, getDoc, getDocs, orderBy, query, setDoc, where } from "firebase/firestore";
import type { FamilyData } from "./familyDataTypes";
import { firestore } from "./firebaseClient";

export type FamilyCalendarSetting = { id: string; family_id: string; state_code: "ACT" | "NSW" | "NT" | "QLD" | "SA" | "TAS" | "VIC" | "WA"; school_level: "primary" | "secondary" | "mixed" | "custom"; school_year: number; term_week1_start: string | null; week_starts_on: number; public_school_baseline: boolean; notes: string | null; created_at: string; updated_at: string; };
export type SchoolTermPeriod = { id: string; family_id: string; school_year: number; term_number: number; term_start: string; term_end: string; label: string | null; is_public_school_baseline: boolean; created_at: string; updated_at: string; };
export type CalendarDayOverride = { id: string; family_id: string; override_date: string; override_type: "public_holiday" | "school_holiday" | "pupil_free_day" | "exam_day" | "school_day" | "custom"; title: string; state_code: string | null; applies_to_member_id: string | null; color_tag: string | null; notes: string | null; created_at: string; updated_at: string; };
export type CalendarDayInfo = { date: string; isSchoolDay: boolean; isHoliday: boolean; weekNumber: number | null; termNumber: number | null; labels: string[]; colorTone: "school" | "holiday" | "exam" | "custom" | "neutral"; };

function nowIso() { return new Date().toISOString(); }
function withId<T>(snapshot: { id: string; data: () => Record<string, unknown> }) { return { id: snapshot.id, ...snapshot.data() } as T; }
function familyCollection(familyId: string, name: string) { return collection(firestore, "families", familyId, name); }
function settingDoc(familyId: string, schoolYear: number) { return doc(firestore, "families", familyId, "family_calendar_settings", String(schoolYear)); }
function termDoc(familyId: string, schoolYear: number, termNumber: number) { return doc(firestore, "families", familyId, "school_term_periods", `${schoolYear}_term_${termNumber}`); }

export function currentSchoolYear() { return new Date().getFullYear(); }
export function toDateKey(date: Date) { return date.toISOString().slice(0, 10); }
export function daysBetween(start: string, end: string) { const a = new Date(`${start}T00:00:00`).getTime(); const b = new Date(`${end}T00:00:00`).getTime(); return Math.floor((b - a) / 86400000); }
export function addDays(dateKey: string, days: number) { const date = new Date(`${dateKey}T00:00:00`); date.setDate(date.getDate() + days); return toDateKey(date); }
export function isWeekend(dateKey: string) { const day = new Date(`${dateKey}T00:00:00`).getDay(); return day === 0 || day === 6; }
export function computeWeekNumber(termStart: string | null, dateKey: string) { if (!termStart) return null; const diff = daysBetween(termStart, dateKey); if (diff < 0) return null; return Math.floor(diff / 7) + 1; }
export function findTermForDate(terms: SchoolTermPeriod[], dateKey: string) { return terms.find((term) => dateKey >= term.term_start && dateKey <= term.term_end) ?? null; }
export function computeCalendarDayInfo(args: { date: string; setting: FamilyCalendarSetting | null; terms: SchoolTermPeriod[]; overrides: CalendarDayOverride[]; }): CalendarDayInfo { const term = findTermForDate(args.terms, args.date); const dateOverrides = args.overrides.filter((item) => item.override_date === args.date); const labels: string[] = []; let colorTone: CalendarDayInfo["colorTone"] = "neutral"; const hasHolidayOverride = dateOverrides.some((item) => ["public_holiday", "school_holiday", "pupil_free_day"].includes(item.override_type)); const hasSchoolDayOverride = dateOverrides.some((item) => item.override_type === "school_day"); const hasExam = dateOverrides.some((item) => item.override_type === "exam_day"); for (const item of dateOverrides) labels.push(item.title); const inTerm = Boolean(term); let isSchoolDay = inTerm && !isWeekend(args.date); if (hasHolidayOverride) isSchoolDay = false; if (hasSchoolDayOverride) isSchoolDay = true; const isHoliday = !isSchoolDay; if (hasExam) colorTone = "exam"; else if (dateOverrides.some((item) => item.override_type === "custom")) colorTone = "custom"; else if (isSchoolDay) colorTone = "school"; else if (isHoliday) colorTone = "holiday"; if (term) labels.unshift(`Term ${term.term_number}`); const week = computeWeekNumber(args.setting?.term_week1_start ?? term?.term_start ?? null, args.date); if (week !== null && inTerm) labels.unshift(`Week ${week}`); return { date: args.date, isSchoolDay, isHoliday, weekNumber: inTerm ? week : null, termNumber: term?.term_number ?? null, labels, colorTone }; }

export async function loadFamilyCalendarSetting(familyId: string, schoolYear = currentSchoolYear()) { const snap = await getDoc(settingDoc(familyId, schoolYear)); return snap.exists() ? withId<FamilyCalendarSetting>(snap) : null; }
export async function upsertFamilyCalendarSetting(args: { data: FamilyData; setting: Partial<FamilyCalendarSetting> & { school_year: number }; }) { const id = String(args.setting.school_year); const now = nowIso(); const row = { id, family_id: args.data.family.id, state_code: args.setting.state_code ?? "SA", school_level: args.setting.school_level ?? "primary", school_year: args.setting.school_year, term_week1_start: args.setting.term_week1_start ?? null, week_starts_on: args.setting.week_starts_on ?? 1, public_school_baseline: args.setting.public_school_baseline ?? true, notes: args.setting.notes ?? null, created_at: now, updated_at: now } as FamilyCalendarSetting; await setDoc(settingDoc(args.data.family.id, args.setting.school_year), row, { merge: true }); return row; }
export async function loadSchoolTerms(familyId: string, schoolYear = currentSchoolYear()) { const snap = await getDocs(query(familyCollection(familyId, "school_term_periods"), where("school_year", "==", schoolYear), orderBy("term_number", "asc"))); return snap.docs.map((docSnap) => withId<SchoolTermPeriod>(docSnap)); }
export async function upsertSchoolTerm(args: { data: FamilyData; schoolYear: number; termNumber: number; termStart: string; termEnd: string; label?: string | null; }) { const now = nowIso(); const id = `${args.schoolYear}_term_${args.termNumber}`; const row: SchoolTermPeriod = { id, family_id: args.data.family.id, school_year: args.schoolYear, term_number: args.termNumber, term_start: args.termStart, term_end: args.termEnd, label: args.label ?? `Term ${args.termNumber}`, is_public_school_baseline: true, created_at: now, updated_at: now }; await setDoc(termDoc(args.data.family.id, args.schoolYear, args.termNumber), row, { merge: true }); return row; }
export async function loadCalendarOverrides(familyId: string, start: string, end: string) { const snap = await getDocs(query(familyCollection(familyId, "calendar_day_overrides"), where("override_date", ">=", start), where("override_date", "<=", end), orderBy("override_date", "asc"))); return snap.docs.map((docSnap) => withId<CalendarDayOverride>(docSnap)); }
export async function createCalendarOverride(args: { data: FamilyData; overrideDate: string; overrideType: CalendarDayOverride["override_type"]; title: string; stateCode?: string | null; appliesToMemberId?: string | null; colorTag?: string | null; notes?: string | null; }) { const ref = doc(familyCollection(args.data.family.id, "calendar_day_overrides")); const now = nowIso(); const row: CalendarDayOverride = { id: ref.id, family_id: args.data.family.id, override_date: args.overrideDate, override_type: args.overrideType, title: args.title, state_code: args.stateCode ?? null, applies_to_member_id: args.appliesToMemberId ?? null, color_tag: args.colorTag ?? null, notes: args.notes ?? null, created_at: now, updated_at: now }; await setDoc(ref, row); return row; }
