/**
 * Family Dock AI parse-command schema.
 *
 * This schema is intentionally "flat" and conservative.
 * For OpenAI Structured Outputs, the action object keeps all possible fields nullable
 * so the schema stays stable while the product evolves.
 */

export const AI_COMMAND_INTENTS = [
  "create_calendar_event",
  "create_homework_task",
  "create_request",
  "create_payment",
  "create_meal_or_recipe",
  "create_learning_record",
  "multi_action",
  "ask_clarifying_question",
  "unknown",
] as const;

export const ACTION_TYPES = [
  "create_calendar_event",
  "create_homework_task",
  "create_request",
  "create_payment",
  "create_meal_or_recipe",
  "create_learning_record",
] as const;

export const familyCommandJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "intent",
    "confidence",
    "language",
    "needs_clarification",
    "clarifying_question",
    "missing_fields",
    "draft_summary",
    "actions",
  ],
  properties: {
    intent: {
      type: "string",
      enum: AI_COMMAND_INTENTS,
    },
    confidence: {
      type: "number",
      minimum: 0,
      maximum: 1,
    },
    language: {
      type: "string",
      enum: ["zh", "en", "mixed", "unknown"],
    },
    needs_clarification: {
      type: "boolean",
    },
    clarifying_question: {
      type: ["string", "null"],
      description:
        "Ask this if required fields are missing or confidence is low. Keep it short and practical.",
    },
    missing_fields: {
      type: "array",
      items: { type: "string" },
    },
    draft_summary: {
      type: "string",
      description: "A short human-readable summary of what the AI thinks the parent wants.",
    },
    actions: {
      type: "array",
      description:
        "One parent sentence can create multiple actions, e.g. course + payment + homework.",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "client_action_id",
          "type",
          "confidence",
          "child_name",
          "title",
          "detail",
          "event_type",
          "request_type",
          "start_date",
          "end_date",
          "start_time",
          "end_time",
          "timezone",
          "weekday",
          "recurrence_rule",
          "place_name",
          "teacher_name",
          "due_date",
          "homework_items",
          "amount",
          "currency",
          "pay_to",
          "reference",
          "meal_type",
          "ingredients",
          "course_name",
          "lesson_title",
          "child_comment",
          "parent_comment",
          "teacher_feedback",
          "strengths",
          "issues",
          "next_steps",
          "expectations",
          "raw_note",
        ],
        properties: {
          client_action_id: {
            type: "string",
            description: "Temporary ID generated by the AI, e.g. act_1.",
          },
          type: {
            type: "string",
            enum: ACTION_TYPES,
          },
          confidence: {
            type: "number",
            minimum: 0,
            maximum: 1,
          },

          child_name: { type: ["string", "null"] },
          title: { type: ["string", "null"] },
          detail: { type: ["string", "null"] },

          event_type: {
            type: ["string", "null"],
            enum: [
              "course",
              "school",
              "family",
              "homework",
              "payment_due",
              "request",
              "temporary",
              "meal",
              "other",
              null,
            ],
          },

          request_type: {
            type: ["string", "null"],
            enum: ["food", "outing", "purchase", "schedule_change", "help", "other", null],
          },

          start_date: {
            type: ["string", "null"],
            description: "YYYY-MM-DD when known.",
          },
          end_date: {
            type: ["string", "null"],
            description: "YYYY-MM-DD when known.",
          },
          start_time: {
            type: ["string", "null"],
            description: "HH:MM 24-hour local time when known.",
          },
          end_time: {
            type: ["string", "null"],
            description: "HH:MM 24-hour local time when known.",
          },
          timezone: {
            type: ["string", "null"],
            description: "IANA timezone, usually Australia/Adelaide.",
          },
          weekday: {
            type: ["string", "null"],
            description: "Monday, Tuesday, etc. Use English weekday names.",
          },
          recurrence_rule: {
            type: ["string", "null"],
            description: "RFC5545 RRULE when recurrence is clear, e.g. RRULE:FREQ=WEEKLY;BYDAY=WE.",
          },

          place_name: { type: ["string", "null"] },
          teacher_name: { type: ["string", "null"] },

          due_date: {
            type: ["string", "null"],
            description: "YYYY-MM-DD when known.",
          },

          homework_items: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["label", "item_type", "is_required"],
              properties: {
                label: { type: "string" },
                item_type: {
                  type: "string",
                  enum: [
                    "checkbox",
                    "text",
                    "photo_upload",
                    "audio_upload",
                    "video_upload",
                    "parent_approval",
                    "teacher_feedback",
                  ],
                },
                is_required: { type: "boolean" },
              },
            },
          },

          amount: {
            type: ["number", "null"],
            minimum: 0,
          },
          currency: {
            type: ["string", "null"],
            description: "Usually AUD.",
          },
          pay_to: { type: ["string", "null"] },
          reference: { type: ["string", "null"] },

          meal_type: {
            type: ["string", "null"],
            enum: ["lunch_box", "dinner", "snack", null],
          },
          ingredients: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["name", "quantity", "category"],
              properties: {
                name: { type: "string" },
                quantity: { type: ["string", "null"] },
                category: { type: ["string", "null"] },
              },
            },
          },

          course_name: { type: ["string", "null"] },
          lesson_title: { type: ["string", "null"] },
          child_comment: { type: ["string", "null"] },
          parent_comment: { type: ["string", "null"] },
          teacher_feedback: { type: ["string", "null"] },
          strengths: {
            type: "array",
            items: { type: "string" },
          },
          issues: {
            type: "array",
            items: { type: "string" },
          },
          next_steps: {
            type: "array",
            items: { type: "string" },
          },
          expectations: {
            type: "array",
            items: { type: "string" },
          },

          raw_note: {
            type: ["string", "null"],
            description: "Any extra context that should not be lost.",
          },
        },
      },
    },
  },
} as const;

export const openAIResponseFormat = {
  type: "json_schema",
  name: "family_dock_parse_command",
  strict: true,
  schema: familyCommandJsonSchema,
} as const;
